# Generated by Django 5.2.11 on 2026-04-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobseekerprofile_nid_card_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'seeker')},
        ),
    ]
